### ISSUE TITLE
Missing plugins

### ISSUE THREAD

**Issue by fniephaus** [hpi-swa/trufflesqueak#3]
- [x] FloatArrayPlugin (progress see #5)
- [ ] LocalePlugin (in-complete, see #40)
- [x] MiscPrimitivePlugin (progress see #4)
- [ ] OSProcess (in-complete, see #39)
- [x] SocketPlugin
- [x] SqueakSSL
- [x] HostWindowPlugin
- [ ] Matrix2x3Plugin (in-complete, see #41)
...
